version: '3'

services:
  app:
    build:
      context: ./node
      dockerfile: Dockerfile
    restart: always
    container_name: app
    volumes:
      - ./node:/usr/src/app
      - /usr/src/app/node_modules
    tty: true
    
    depends_on: 
      - db    
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s docker-entrypoint.sh
    command: "node ./index.js" 
    networks:
      - node-network

  db:
    image: mysql:5.7               
    command: --innodb-use-native-aio=0    
    restart: always
    container_name: db
    tty: true
    volumes:
      - ./mysql:/data
      - ./node/.docker/mysql:/docker-entrypoint-initdb.d
    environment: 
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root 
    networks:
      - node-network
     

  nginx:
    restart: always
    build: 
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginx
    networks:
      - node-network
    ports:
      - "8080:80"
    depends_on:
      - app


networks:
  node-network:
    driver: bridge  
